language: emacs-lisp
git:
  # deactivate ci-travis's automatic dealing with submodules when cloning - http://docs.travis-ci.com/user/build-configuration/#Git-Submodules
  submodules: false
before_install:
  # to permit to change the git url to public ones
  - sed -e 's/git@github.com:/git@github.com\//g' -i .gitmodules
  # - mv Cask Cask.origin
  # - grep -v "marmalade" Cask.origin > Cask
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs-snapshot-el emacs-snapshot-gtk emacs-snapshot;
    fi
  - if [ "$EMACS" = 'emacs24' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs24 emacs24-el emacs24-common-non-dfsg;
    fi
  - ls
  - pwd
  # - deploy emacs-live
  - git clone git@github.com:overtone/emacs-live.git ~/.emacs.d
  # - deploy emacs-live-packs
  - $(pwd)/deploy.sh
  # - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  # - export PATH="/home/travis/.cask/bin:$PATH"
  # - cask
env:
  #- EMACS=emacs
  - EMACS=emacs24
  # - EMACS=emacs-snapshot
script:
  ./run-travis-ci.sh
